apiVersion: v1
kind: Service
metadata:
  name: hello-lb
spec:
  type: LoadBalancer
  externalIPs:
    - 172.31.71.218
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
  selector:
    role: hello
