#cloud-config
package_update: true
packages:
  - docker.io
write_files:
  - path: /root/index.html
    content: |
      Sos un capo de terraform
runcmd:
  - docker run -d -v /root/index.html:/usr/share/nginx/html/index.html -p 80:80 nginx
