FROM alpine

RUN apk add --update --no-cache git openssh-client

RUN mkdir -p -m 0600 ~/.ssh && \
  ssh-keyscan github.com >> ~/.ssh/known_hosts

COPY id_rsa ~/.ssh/

RUN git clone git@github.com:pablokbs/privado.git
