# kustomize build . | kubectl apply -f -

resources:
- quickstart.yaml #gatewayClass y gateway

helmCharts:
- name: gateway-helm
  namespace: envoy-gateway-system
  repo: oci://docker.io/envoyproxy
  version: 1.4.1