services:  
  openclaw-gateway:
    build: openclaw-repo # Este repo se descarga de https://github.com/openclaw/openclaw
    environment:
      HOME: /home/node
      TERM: xterm-256color
    volumes:
      - ./openclaw/config:/home/node/.openclaw
      - ./openclaw/workspace:/home/node/.openclaw/workspace
    ports:
      - "${OPENCLAW_GATEWAY_PORT:-18789}:18789"
      - "${OPENCLAW_BRIDGE_PORT:-18790}:18790"
    init: true
    restart: unless-stopped
    command:
      [
        "node",
        "dist/index.js",
        "gateway",
        "--bind",
        "${OPENCLAW_GATEWAY_BIND:-lan}",
        "--port",
        "${OPENCLAW_GATEWAY_PORT:-18789}",
        "--allow-unconfigured",
      ]

  openclaw-cli:
    build: openclaw-repo
    environment:
      HOME: /home/node
      TERM: xterm-256color
      BROWSER: echo
    volumes:
      - ./openclaw/config:/home/node/.openclaw
      - ./openclaw/workspace:/home/node/.openclaw/workspace
    stdin_open: true
    tty: true
    init: true
    entrypoint: ["node", "dist/index.js"]

  browserless-chromium:
    image: ghcr.io/browserless/chromium:v2.39.0
    expose:
      - "3000"
