name: Integration Tests

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master ]

jobs:
  integration-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: varios/21/integration

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        cache: 'pip'
        cache-dependency-path: varios/21/integration/requirements.txt

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run integration tests
      run: pytest -v
      env:
        DATABASE_URL: postgresql://postgres:postgres@localhost:5432/testdb 