name: Node.js CI

on:
  push:
    branches: [ master, test ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: varios/21

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js 18.x
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: varios/21/package.json
        
    - name: Generate package-lock.json
      run: npm install --package-lock-only
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run tests
      run: npm test 